framework:
    rate_limiter:
        login:
            policy: 'sliding_window'
            limit: 5
            interval: '1 minute'
        register:
            policy: 'fixed_window'
            limit: 3
            interval: '5 minutes'
        contact:
            policy: 'sliding_window'
            limit: 2
            interval: '55 minute'
        collection:
            policy: 'sliding_window'
            limit: 3
            interval: '10 minute'