version: "3.8"

services:
  ### 🐘 PostgreSQL ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - database_data:/var/lib/postgresql/data:rw

  ### ⚙️ Symfony App ###
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_healthy
      mailpit:
        condition: service_started
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/var
    ports:
      - "8000:8000"
    environment:
      APP_ENV: dev
      DATABASE_URL: "postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-!ChangeMe!}@database:5432/${POSTGRES_DB:-app}?serverVersion=16&charset=utf8"
      MAILER_DSN: smtp://mailpit:1025
    command: php -S 0.0.0.0:8000 -t public

  ### 📬 Mailpit (serveur SMTP pour dev) ###
  mailpit:
    image: axllent/mailpit
    ports:
      - "1025:1025"  # Pour l'envoi SMTP depuis Symfony
      - "8025:8025"  # Interface web ici → http://localhost:8025

volumes:
  database_data:
